Repository Team-Cartographer/SUITS-2024-LMCC, pull requests merged in 2024-01, with the labels that each got.

#6 TSS Update
  README.md
  Setup.ps1
  client/.gitignore
  client/api/fetchServer.ts
  server/config/check_tss.py
  server/config/startup.py
  server/routes/mission.py
  server/routes/tss.py
  server/server.py
  server/templates/404.html
  server/templates/directory.html
  start.sh
Labels: enhancement

#21 Conformed Python Server to a RESTful API
  .vscode/settings.json
  README.md
  client/api/fetchServer.ts
  client/app/screen_two/page.tsx
  client/components/ui/map.tsx
  client/components/ui/timing.tsx
  client/package-lock.json
  client/package.json
  server/.gitignore
  server/api/api.py
  server/api/functions/astar.py
  server/api/getters.py
  server/api/posters.py
  server/api/utils.py
  server/config/requirements.txt
  server/config/startup.py
  server/functions/astar.py
  server/images/rockYardMap.png
  server/server.py
  server/temp.txt
  server/templates/directory.html
  testbench.py
Labels: enhancement

#25 refactored A* functionality
  server/api/functions/astar.py
  server/api/functions/imaging.py
Labels: upgrade

#30 Added docstrings and type hinting to server folder
  server/api/api.py
  server/api/functions/astar.py
  server/api/functions/imaging.py
  server/api/posters.py
  server/api/utils.py
  server/config/open_app.py
  server/config/startup.py
  server/routes/mission.py
  server/routes/tests.py
  server/routes/tss.py
  server/server.py
Labels: documentation
